name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04

    steps:
      - uses: googleapis/release-please-action@v4
        id: release

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  build:
    needs: [release-please]
    if: needs.release-please.outputs.release_created == 'true'
    uses: ./.github/workflows/build.yml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}

  release:
    runs-on: ubuntu-22.04
    needs: [release-please, build]
    if: needs.release-please.outputs.release_created == 'true'
    env:
      TAG_NAME: ${{ needs.release-please.outputs.tag_name }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: rime-wanxiang-dist-${{ github.ref_name }}
          path: artifact

      - name: Generate release note
        id: release-note
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash scripts/generate-release-note.sh > release-note.md

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: "${{ env.TAG_NAME }} Rime万象拼音输入方案"
          bodyFile: release-note.md
          artifacts: artifact/rime-wanxiang-*.zip
          draft: false
          allowUpdates: true
